### ISSUE TITLE
PACKAGE LINKS DONT FUCKING WORK

### ISSUE THREAD

**Issue by Deniied** [MaximumADHD/Roblox-File-Format#10]
I AM VERY VERY ANGRY I TRY TO USE A LIBRARY WRITTEN BY A STUPID FUCKING GINGER TO HONOUR PLAYBOY CARTI. I TRY TO USE PACKAGELINKS AND IT SHITS ITSELF AND CORRUPTS, I CANT EVEN ADD A FUCKING PACKAGEID. IM CRYING RIGHT NOW.

**Comment by MaximumADHD** [comment]
Package functionality is not included with this library, only the instances that back it.

You are free to parse the PackageIdSerialize URI to get an AssetId to work with against `https://assetdelivery.roblox.com/v1/asset/?ID=`

Note that you’ll need to scrape your authentication cookies from `HKEY_CURRENT_USER\Software\Roblox\RobloxStudioBrowser\roblox.com`

Have a great day, and also go fuck yourself.

**Comment by brendenconner** [comment]
real

**Comment by SomeDudeOnGithub** [comment]
very
