### ISSUE TITLE
System.ArgumentException: '►', hexadecimal value 0x10, is an invalid character.

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [MaximumADHD/Roblox-File-Format#13]
I wrote a .NET 4.7.2 program for converting multiple RBXM files to RBXMX (since manually converting them takes a long amount of time, I've did it once and never want to deal with it again), however when I try to convert a rbxm file I get the following error below:

```
Unhandled Exception: System.ArgumentException: '►', hexadecimal value 0x10, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
   at System.Xml.XmlEncodedRawTextWriter.WriteCDataSection(String text)
   at System.Xml.XmlEncodedRawTextWriter.WriteCData(String text)
   at System.Xml.XmlEncodedRawTextWriterIndent.WriteCData(String text)
   at System.Xml.XmlWellFormedWriter.WriteCData(String text)
   at System.Xml.XmlCDataSection.WriteTo(XmlWriter w)
   at System.Xml.XmlElement.WriteElementTo(XmlWriter writer, XmlElement e)
   at System.Xml.XmlElement.WriteTo(XmlWriter w)
   at System.Xml.XmlDocument.WriteContentTo(XmlWriter xw)
   at RobloxFiles.XmlRobloxFile.Save(Stream stream)
   at RobloxFiles.RobloxFile.Save(String filePath)
   at RBXMtoRBXMX.Program.Main(String[] args) in C:\<stuff>\RBXMtoRBXMX\RBXMtoRBXMX\Program.cs:line 45
```

The following lines of code handle the conversion
```csharp
case BinaryRobloxFile:
    {
        Console.WriteLine("Converting " + FileName);
        RobloxFile XmlRbxModelFile = new XmlRobloxFile();
        foreach(Instance inst in RbxModelFile.GetChildren()) inst.Parent = XmlRbxModelFile;
        XmlRbxModelFile.Save(FileName.Replace(".rbxm", ".rbxmx"));
        break;
    }
```

Edit:
The error comes from this line:
```csharp
XmlRbxModelFile.Save(FileName.Replace(".rbxm", ".rbxmx"));
```
The file name does not have special characters except whitespace

**Comment by Hesam-s** [comment]
Instead of that line, try these lines:
                string SavePath = FileName.Replace(".rbxm", ".rbxmx");
                XmlRbxModelFile;.Save(SavePath);

**Comment by MaximumADHD** [comment]
Interesting edge case for sure. It seems you have a data link escape character in some property of your data. I’m not even sure if Roblox would save this file as XML if you did it manually. 

If you can provide a repro I can consult some other folks to see what the best course would be here. I think you might be better off just removing the bad character from your data, where-ever it is.

**Comment by RealEthanPlayzDev** [comment]
> Instead of that line, try these lines:
string SavePath = FileName.Replace(".rbxm", ".rbxmx");
XmlRbxModelFile;.Save(SavePath);

This was the previous code before I shortened it, it exhibits the same issue

> I’m not even sure if Roblox would save this file as XML if you did it manually.

Well, Roblox did since I saved them as rbxmx manually

> If you can provide a repro I can consult some other folks to see what the best course would be here. I think you might be better off just removing the bad character from your data, where-ever it is.

Not gonna bother removing them manually to be honest (since I don't care, I just need them in rbxmx), heres the original rbxm files that has the issue: (I wrapped the conversion in a try-catch block to catch the issues and these failed)
[LCs.zip](https://github.com/MaximumADHD/Roblox-File-Format/files/9276696/LCs.zip) (GitHub doesn't support rbxm so I had to zip them)
