### ISSUE TITLE
CollisionGroup "Default" doesn't exist

### ISSUE THREAD

**Issue by GrowtopiaJe** [MaximumADHD/Roblox-File-Format#16]
When i save place, meshes and UnionOperations rotation are messed up in wrong direction, and when i open saved file, i can't select anything and i get this console error  "RaycastParam's CollisionGroup 'Default���Q�' does not exist ", "Script 'builtin_MoveDragger.rbxm.MoveDragger.Packages.DraggerSchemaCore.getMouseTarget', Line 17 "
Is that bug?

**Comment by MaximumADHD** [comment]
This has been on my radar, I just haven’t had time to address it.
It has something to do with a breaking compatibility change Roblox made.
Will investigate when I get a chance.

**Comment by MaximumADHD** [comment]
Is this still happening btw? I *think* the update might’ve fixed it.
