### ISSUE TITLE
RBXM & RBXL issues when opening after save.

### ISSUE THREAD

**Issue by IsEmil** [MaximumADHD/Roblox-File-Format#18]
Whenever I open a rbxm or rbxl file and then any scripts in the file that I edit and then save, when I try and open the file I get this error:

readInt64Vector offset is out of bounds while reading 8 bytes, offset=21, datasize=21 << int64/bpfSecurityCapabilities vector, size=1 << property values, name=Capabilities, type=Capabilities << chunk#80[PROP], property with typeIndex=0, type=AnalyticsService"

when I test this with rbxlx or rbxmx than it works fine.

**Comment by MaximumADHD** [comment]
This should be fixed now. I added support for SecurityCapabilities.

**Comment by dv1m** [comment]
It shows this now

"Unexpected format 29 (expected 1 or 28) while deserializing a string << property values, name=Source, type=Source << chunk#337[PROP], property with typeIndex=19, type=LocalScript"

**Comment by IsEmil** [comment]
> It shows this now
> 
> "Unexpected format 29 (expected 1 or 28) while deserializing a string << property values, name=Source, type=Source << chunk#337[PROP], property with typeIndex=19, type=LocalScript"
> 
> (does this with both ModuleScripts and Scripts)

When I tried modifying a Script I got the same issue:

"Unexpected format 29 (expected 1 or 28) while deserializing a string << property values, name=Source, type=Source << chunk#621[PROP], property with typeIndex=38, type=Script"

**Comment by MaximumADHD** [comment]
ooh, fixing.

**Comment by MaximumADHD** [comment]
Apologies for that, it should be good.

**Comment by IsEmil** [comment]
Works now thanks 👋
